[[edge_functions]]
path = "/home-office-ideas-that-will-inspire-you/"
function = "gone"

[[edge_functions]]
path = "/home-office-ideas-that-will-inspire-you"
function = "gone"

[[edge_functions]]
path = "/staycation-ideas-your-family-will-enjoy/"
function = "gone"

[[edge_functions]]
path = "/staycation-ideas-your-family-will-enjoy"
function = "gone"

[[edge_functions]]
path = "/top-10-interior-design-trends-in-2020-to-freshen-up-your-home/"
function = "gone"

[[edge_functions]]
path = "/top-10-interior-design-trends-in-2020-to-freshen-up-your-home"
function = "gone"

[[edge_functions]]
path = "/phoenix-home-loan-payoff-vision-board/"
function = "gone"

[[edge_functions]]
path = "/phoenix-home-loan-payoff-vision-board"
function = "gone"

[[edge_functions]]
path = "/make-home-attractive-before-putting-on-market/"
function = "gone"

[[edge_functions]]
path = "/make-home-attractive-before-putting-on-market"
function = "gone"

[[edge_functions]]
path = "/virtual-showings-what-you-need-to-know/"
function = "gone"

[[edge_functions]]
path = "/virtual-showings-what-you-need-to-know"
function = "gone"
